[package]
name = "markdown_preview"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/markdown_preview.rs"

[features]
test-support = []

[[bin]]
name = "mdview"
path = "src/bin/mdview.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
editor.workspace = true
fs.workspace = true
gpui.workspace = true
language.workspace = true
log.workspace = true
markdown.workspace = true
paths.workspace = true
project.workspace = true
settings.workspace = true
theme_settings.workspace = true
ui.workspace = true
urlencoding.workspace = true
util.workspace = true
workspace.workspace = true
worktree.workspace = true
zed_actions.workspace = true

[dev-dependencies]
tempfile.workspace = true
